apiVersion: v1
kind: ConfigMap
metadata:
  name: get-caramel-config
data:
  APP_ENV: "staging"
  AUTH_ACCESS_TTL_SEC: "900"
  AUTH_REFRESH_TTL_SEC: "604800"
  AUTH_SERVICE_PORT: "4001"
  CATALOG_SERVICE_PORT: "4002"
  ORDER_SERVICE_PORT: "4003"
  PAYMENT_SERVICE_PORT: "4004"
  DELIVERY_SERVICE_PORT: "4005"
  GATEWAY_PORT: "4000"
  AUTH_SERVICE_URL: "http://auth-service:4001"
  CATALOG_SERVICE_URL: "http://catalog-service:4002"
  ORDER_SERVICE_URL: "http://order-service:4003"
  PAYMENT_SERVICE_URL: "http://payment-service:4004"
  DELIVERY_SERVICE_URL: "http://delivery-service:4005"
  PAYMENT_PROVIDER: "local"
